export type Language = "python" | "javascript" | "java" | "cpp" | "go";

export type StarterCodeMap = Record<Language, string>;

const DEFAULT: StarterCodeMap = {
  python: "class Solution:\n    def solve(self):\n        pass\n",
  javascript: "var solve = function() {\n    \n};\n",
  java: "class Solution {\n    public void solve() {\n        \n    }\n}\n",
  cpp: "class Solution {\npublic:\n    void solve() {\n        \n    }\n};\n",
  go: "func solve() {\n    \n}\n",
};

const STARTER_CODE: Record<string, StarterCodeMap> = {
  "two-sum": {
    python: "from typing import List\n\nclass Solution:\n    def twoSum(self, nums: List[int], target: int) -> List[int]:\n        pass\n",
    javascript: "/**\n * @param {number[]} nums\n * @param {number} target\n * @return {number[]}\n */\nvar twoSum = function(nums, target) {\n    \n};\n",
    java: "class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n        \n    }\n};\n",
    go: "func twoSum(nums []int, target int) []int {\n    \n}\n",
  },
  "best-time-to-buy-and-sell-stock": {
    python: "from typing import List\n\nclass Solution:\n    def maxProfit(self, prices: List[int]) -> int:\n        pass\n",
    javascript: "/**\n * @param {number[]} prices\n * @return {number}\n */\nvar maxProfit = function(prices) {\n    \n};\n",
    java: "class Solution {\n    public int maxProfit(int[] prices) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int maxProfit(vector<int>& prices) {\n        \n    }\n};\n",
    go: "func maxProfit(prices []int) int {\n    \n}\n",
  },
  "contains-duplicate": {
    python: "from typing import List\n\nclass Solution:\n    def containsDuplicate(self, nums: List[int]) -> bool:\n        pass\n",
    javascript: "/**\n * @param {number[]} nums\n * @return {boolean}\n */\nvar containsDuplicate = function(nums) {\n    \n};\n",
    java: "class Solution {\n    public boolean containsDuplicate(int[] nums) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    bool containsDuplicate(vector<int>& nums) {\n        \n    }\n};\n",
    go: "func containsDuplicate(nums []int) bool {\n    \n}\n",
  },
  "product-of-array-except-self": {
    python: "from typing import List\n\nclass Solution:\n    def productExceptSelf(self, nums: List[int]) -> List[int]:\n        pass\n",
    javascript: "/**\n * @param {number[]} nums\n * @return {number[]}\n */\nvar productExceptSelf = function(nums) {\n    \n};\n",
    java: "class Solution {\n    public int[] productExceptSelf(int[] nums) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    vector<int> productExceptSelf(vector<int>& nums) {\n        \n    }\n};\n",
    go: "func productExceptSelf(nums []int) []int {\n    \n}\n",
  },
  "maximum-subarray": {
    python: "from typing import List\n\nclass Solution:\n    def maxSubArray(self, nums: List[int]) -> int:\n        pass\n",
    javascript: "/**\n * @param {number[]} nums\n * @return {number}\n */\nvar maxSubArray = function(nums) {\n    \n};\n",
    java: "class Solution {\n    public int maxSubArray(int[] nums) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int maxSubArray(vector<int>& nums) {\n        \n    }\n};\n",
    go: "func maxSubArray(nums []int) int {\n    \n}\n",
  },
  "valid-palindrome": {
    python: "class Solution:\n    def isPalindrome(self, s: str) -> bool:\n        pass\n",
    javascript: "/**\n * @param {string} s\n * @return {boolean}\n */\nvar isPalindrome = function(s) {\n    \n};\n",
    java: "class Solution {\n    public boolean isPalindrome(String s) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    bool isPalindrome(string s) {\n        \n    }\n};\n",
    go: "func isPalindrome(s string) bool {\n    \n}\n",
  },
  "3sum": {
    python: "from typing import List\n\nclass Solution:\n    def threeSum(self, nums: List[int]) -> List[List[int]]:\n        pass\n",
    javascript: "/**\n * @param {number[]} nums\n * @return {number[][]}\n */\nvar threeSum = function(nums) {\n    \n};\n",
    java: "import java.util.*;\n\nclass Solution {\n    public List<List<Integer>> threeSum(int[] nums) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    vector<vector<int>> threeSum(vector<int>& nums) {\n        \n    }\n};\n",
    go: "func threeSum(nums []int) [][]int {\n    \n}\n",
  },
  "container-with-most-water": {
    python: "from typing import List\n\nclass Solution:\n    def maxArea(self, height: List[int]) -> int:\n        pass\n",
    javascript: "/**\n * @param {number[]} height\n * @return {number}\n */\nvar maxArea = function(height) {\n    \n};\n",
    java: "class Solution {\n    public int maxArea(int[] height) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int maxArea(vector<int>& height) {\n        \n    }\n};\n",
    go: "func maxArea(height []int) int {\n    \n}\n",
  },
  "best-time-to-buy-and-sell-stock-ii": {
    python: "from typing import List\n\nclass Solution:\n    def maxProfit(self, prices: List[int]) -> int:\n        pass\n",
    javascript: "/**\n * @param {number[]} prices\n * @return {number}\n */\nvar maxProfit = function(prices) {\n    \n};\n",
    java: "class Solution {\n    public int maxProfit(int[] prices) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int maxProfit(vector<int>& prices) {\n        \n    }\n};\n",
    go: "func maxProfit(prices []int) int {\n    \n}\n",
  },
  "longest-substring-without-repeating-characters": {
    python: "class Solution:\n    def lengthOfLongestSubstring(self, s: str) -> int:\n        pass\n",
    javascript: "/**\n * @param {string} s\n * @return {number}\n */\nvar lengthOfLongestSubstring = function(s) {\n    \n};\n",
    java: "class Solution {\n    public int lengthOfLongestSubstring(String s) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    int lengthOfLongestSubstring(string s) {\n        \n    }\n};\n",
    go: "func lengthOfLongestSubstring(s string) int {\n    \n}\n",
  },
  "minimum-window-substring": {
    python: "class Solution:\n    def minWindow(self, s: str, t: str) -> str:\n        pass\n",
    javascript: "/**\n * @param {string} s\n * @param {string} t\n * @return {string}\n */\nvar minWindow = function(s, t) {\n    \n};\n",
    java: "class Solution {\n    public String minWindow(String s, String t) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    string minWindow(string s, string t) {\n        \n    }\n};\n",
    go: "func minWindow(s string, t string) string {\n    \n}\n",
  },
  "binary-search": {
    python: "from typing import List\n\nclass Solution:\n    def search(self, nums: List[int], target: int) -> int:\n        pass\n",
    javascript: "/**\n * @param {number[]} nums\n * @param {number} target\n * @return {number}\n */\nvar search = function(nums, target) {\n    \n};\n",
    java: "class Solution {\n    public int search(int[] nums, int target) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int search(vector<int>& nums, int target) {\n        \n    }\n};\n",
    go: "func search(nums []int, target int) int {\n    \n}\n",
  },
  "search-in-rotated-sorted-array": {
    python: "from typing import List\n\nclass Solution:\n    def search(self, nums: List[int], target: int) -> int:\n        pass\n",
    javascript: "/**\n * @param {number[]} nums\n * @param {number} target\n * @return {number}\n */\nvar search = function(nums, target) {\n    \n};\n",
    java: "class Solution {\n    public int search(int[] nums, int target) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int search(vector<int>& nums, int target) {\n        \n    }\n};\n",
    go: "func search(nums []int, target int) int {\n    \n}\n",
  },
  "find-minimum-in-rotated-sorted-array": {
    python: "from typing import List\n\nclass Solution:\n    def findMin(self, nums: List[int]) -> int:\n        pass\n",
    javascript: "/**\n * @param {number[]} nums\n * @return {number}\n */\nvar findMin = function(nums) {\n    \n};\n",
    java: "class Solution {\n    public int findMin(int[] nums) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int findMin(vector<int>& nums) {\n        \n    }\n};\n",
    go: "func findMin(nums []int) int {\n    \n}\n",
  },
  "reverse-linked-list": {
    python: "from typing import Optional\n\n# Definition for singly-linked list.\n# class ListNode:\n#     def __init__(self, val=0, next=None):\n#         self.val = val\n#         self.next = next\n\nclass Solution:\n    def reverseList(self, head: Optional[ListNode]) -> Optional[ListNode]:\n        pass\n",
    javascript: "/**\n * @param {ListNode} head\n * @return {ListNode}\n */\nvar reverseList = function(head) {\n    \n};\n",
    java: "class Solution {\n    public ListNode reverseList(ListNode head) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    ListNode* reverseList(ListNode* head) {\n        \n    }\n};\n",
    go: "func reverseList(head *ListNode) *ListNode {\n    \n}\n",
  },
  "merge-two-sorted-lists": {
    python: "from typing import Optional\n\nclass Solution:\n    def mergeTwoLists(self, list1: Optional[ListNode], list2: Optional[ListNode]) -> Optional[ListNode]:\n        pass\n",
    javascript: "var mergeTwoLists = function(list1, list2) {\n    \n};\n",
    java: "class Solution {\n    public ListNode mergeTwoLists(ListNode list1, ListNode list2) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    ListNode* mergeTwoLists(ListNode* list1, ListNode* list2) {\n        \n    }\n};\n",
    go: "func mergeTwoLists(list1 *ListNode, list2 *ListNode) *ListNode {\n    \n}\n",
  },
  "linked-list-cycle": {
    python: "from typing import Optional\n\nclass Solution:\n    def hasCycle(self, head: Optional[ListNode]) -> bool:\n        pass\n",
    javascript: "var hasCycle = function(head) {\n    \n};\n",
    java: "class Solution {\n    public boolean hasCycle(ListNode head) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    bool hasCycle(ListNode *head) {\n        \n    }\n};\n",
    go: "func hasCycle(head *ListNode) bool {\n    \n}\n",
  },
  "remove-nth-node-from-end-of-list": {
    python: "from typing import Optional\n\nclass Solution:\n    def removeNthFromEnd(self, head: Optional[ListNode], n: int) -> Optional[ListNode]:\n        pass\n",
    javascript: "var removeNthFromEnd = function(head, n) {\n    \n};\n",
    java: "class Solution {\n    public ListNode removeNthFromEnd(ListNode head, int n) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    ListNode* removeNthFromEnd(ListNode* head, int n) {\n        \n    }\n};\n",
    go: "func removeNthFromEnd(head *ListNode, n int) *ListNode {\n    \n}\n",
  },
  "valid-parentheses": {
    python: "class Solution:\n    def isValid(self, s: str) -> bool:\n        pass\n",
    javascript: "/**\n * @param {string} s\n * @return {boolean}\n */\nvar isValid = function(s) {\n    \n};\n",
    java: "class Solution {\n    public boolean isValid(String s) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    bool isValid(string s) {\n        \n    }\n};\n",
    go: "func isValid(s string) bool {\n    \n}\n",
  },
  "daily-temperatures": {
    python: "from typing import List\n\nclass Solution:\n    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:\n        pass\n",
    javascript: "/**\n * @param {number[]} temperatures\n * @return {number[]}\n */\nvar dailyTemperatures = function(temperatures) {\n    \n};\n",
    java: "class Solution {\n    public int[] dailyTemperatures(int[] temperatures) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    vector<int> dailyTemperatures(vector<int>& temperatures) {\n        \n    }\n};\n",
    go: "func dailyTemperatures(temperatures []int) []int {\n    \n}\n",
  },
  "maximum-depth-of-binary-tree": {
    python: "from typing import Optional\n\nclass Solution:\n    def maxDepth(self, root: Optional[TreeNode]) -> int:\n        pass\n",
    javascript: "var maxDepth = function(root) {\n    \n};\n",
    java: "class Solution {\n    public int maxDepth(TreeNode root) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    int maxDepth(TreeNode* root) {\n        \n    }\n};\n",
    go: "func maxDepth(root *TreeNode) int {\n    \n}\n",
  },
  "invert-binary-tree": {
    python: "from typing import Optional\n\nclass Solution:\n    def invertTree(self, root: Optional[TreeNode]) -> Optional[TreeNode]:\n        pass\n",
    javascript: "var invertTree = function(root) {\n    \n};\n",
    java: "class Solution {\n    public TreeNode invertTree(TreeNode root) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    TreeNode* invertTree(TreeNode* root) {\n        \n    }\n};\n",
    go: "func invertTree(root *TreeNode) *TreeNode {\n    \n}\n",
  },
  "same-tree": {
    python: "from typing import Optional\n\nclass Solution:\n    def isSameTree(self, p: Optional[TreeNode], q: Optional[TreeNode]) -> bool:\n        pass\n",
    javascript: "var isSameTree = function(p, q) {\n    \n};\n",
    java: "class Solution {\n    public boolean isSameTree(TreeNode p, TreeNode q) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    bool isSameTree(TreeNode* p, TreeNode* q) {\n        \n    }\n};\n",
    go: "func isSameTree(p *TreeNode, q *TreeNode) bool {\n    \n}\n",
  },
  "binary-tree-level-order-traversal": {
    python: "from typing import Optional, List\n\nclass Solution:\n    def levelOrder(self, root: Optional[TreeNode]) -> List[List[int]]:\n        pass\n",
    javascript: "var levelOrder = function(root) {\n    \n};\n",
    java: "import java.util.*;\n\nclass Solution {\n    public List<List<Integer>> levelOrder(TreeNode root) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    vector<vector<int>> levelOrder(TreeNode* root) {\n        \n    }\n};\n",
    go: "func levelOrder(root *TreeNode) [][]int {\n    \n}\n",
  },
  "validate-binary-search-tree": {
    python: "from typing import Optional\n\nclass Solution:\n    def isValidBST(self, root: Optional[TreeNode]) -> bool:\n        pass\n",
    javascript: "var isValidBST = function(root) {\n    \n};\n",
    java: "class Solution {\n    public boolean isValidBST(TreeNode root) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    bool isValidBST(TreeNode* root) {\n        \n    }\n};\n",
    go: "func isValidBST(root *TreeNode) bool {\n    \n}\n",
  },
  "lowest-common-ancestor-of-a-binary-search-tree": {
    python: "class Solution:\n    def lowestCommonAncestor(self, root: 'TreeNode', p: 'TreeNode', q: 'TreeNode') -> 'TreeNode':\n        pass\n",
    javascript: "var lowestCommonAncestor = function(root, p, q) {\n    \n};\n",
    java: "class Solution {\n    public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    TreeNode* lowestCommonAncestor(TreeNode* root, TreeNode* p, TreeNode* q) {\n        \n    }\n};\n",
    go: "func lowestCommonAncestor(root, p, q *TreeNode) *TreeNode {\n    \n}\n",
  },
  "kth-largest-element-in-an-array": {
    python: "from typing import List\n\nclass Solution:\n    def findKthLargest(self, nums: List[int], k: int) -> int:\n        pass\n",
    javascript: "var findKthLargest = function(nums, k) {\n    \n};\n",
    java: "class Solution {\n    public int findKthLargest(int[] nums, int k) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int findKthLargest(vector<int>& nums, int k) {\n        \n    }\n};\n",
    go: "func findKthLargest(nums []int, k int) int {\n    \n}\n",
  },
  "top-k-frequent-elements": {
    python: "from typing import List\n\nclass Solution:\n    def topKFrequent(self, nums: List[int], k: int) -> List[int]:\n        pass\n",
    javascript: "var topKFrequent = function(nums, k) {\n    \n};\n",
    java: "class Solution {\n    public int[] topKFrequent(int[] nums, int k) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    vector<int> topKFrequent(vector<int>& nums, int k) {\n        \n    }\n};\n",
    go: "func topKFrequent(nums []int, k int) []int {\n    \n}\n",
  },
  "number-of-islands": {
    python: "from typing import List\n\nclass Solution:\n    def numIslands(self, grid: List[List[str]]) -> int:\n        pass\n",
    javascript: "var numIslands = function(grid) {\n    \n};\n",
    java: "class Solution {\n    public int numIslands(char[][] grid) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int numIslands(vector<vector<char>>& grid) {\n        \n    }\n};\n",
    go: "func numIslands(grid [][]byte) int {\n    \n}\n",
  },
  "clone-graph": {
    python: "from typing import Optional\n\nclass Solution:\n    def cloneGraph(self, node: Optional['Node']) -> Optional['Node']:\n        pass\n",
    javascript: "var cloneGraph = function(node) {\n    \n};\n",
    java: "class Solution {\n    public Node cloneGraph(Node node) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    Node* cloneGraph(Node* node) {\n        \n    }\n};\n",
    go: "func cloneGraph(node *Node) *Node {\n    \n}\n",
  },
  "course-schedule": {
    python: "from typing import List\n\nclass Solution:\n    def canFinish(self, numCourses: int, prerequisites: List[List[int]]) -> bool:\n        pass\n",
    javascript: "var canFinish = function(numCourses, prerequisites) {\n    \n};\n",
    java: "class Solution {\n    public boolean canFinish(int numCourses, int[][] prerequisites) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    bool canFinish(int numCourses, vector<vector<int>>& prerequisites) {\n        \n    }\n};\n",
    go: "func canFinish(numCourses int, prerequisites [][]int) bool {\n    \n}\n",
  },
  "climbing-stairs": {
    python: "class Solution:\n    def climbStairs(self, n: int) -> int:\n        pass\n",
    javascript: "var climbStairs = function(n) {\n    \n};\n",
    java: "class Solution {\n    public int climbStairs(int n) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    int climbStairs(int n) {\n        \n    }\n};\n",
    go: "func climbStairs(n int) int {\n    \n}\n",
  },
  "house-robber": {
    python: "from typing import List\n\nclass Solution:\n    def rob(self, nums: List[int]) -> int:\n        pass\n",
    javascript: "var rob = function(nums) {\n    \n};\n",
    java: "class Solution {\n    public int rob(int[] nums) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int rob(vector<int>& nums) {\n        \n    }\n};\n",
    go: "func rob(nums []int) int {\n    \n}\n",
  },
  "coin-change": {
    python: "from typing import List\n\nclass Solution:\n    def coinChange(self, coins: List[int], amount: int) -> int:\n        pass\n",
    javascript: "var coinChange = function(coins, amount) {\n    \n};\n",
    java: "class Solution {\n    public int coinChange(int[] coins, int amount) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int coinChange(vector<int>& coins, int amount) {\n        \n    }\n};\n",
    go: "func coinChange(coins []int, amount int) int {\n    \n}\n",
  },
  "longest-common-subsequence": {
    python: "class Solution:\n    def longestCommonSubsequence(self, text1: str, text2: str) -> int:\n        pass\n",
    javascript: "var longestCommonSubsequence = function(text1, text2) {\n    \n};\n",
    java: "class Solution {\n    public int longestCommonSubsequence(String text1, String text2) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    int longestCommonSubsequence(string text1, string text2) {\n        \n    }\n};\n",
    go: "func longestCommonSubsequence(text1 string, text2 string) int {\n    \n}\n",
  },
  "word-break": {
    python: "from typing import List\n\nclass Solution:\n    def wordBreak(self, s: str, wordDict: List[str]) -> bool:\n        pass\n",
    javascript: "var wordBreak = function(s, wordDict) {\n    \n};\n",
    java: "import java.util.*;\n\nclass Solution {\n    public boolean wordBreak(String s, List<String> wordDict) {\n        \n    }\n}\n",
    cpp: "#include <vector>\n#include <string>\nusing namespace std;\n\nclass Solution {\npublic:\n    bool wordBreak(string s, vector<string>& wordDict) {\n        \n    }\n};\n",
    go: "func wordBreak(s string, wordDict []string) bool {\n    \n}\n",
  },
  "longest-increasing-subsequence": {
    python: "from typing import List\n\nclass Solution:\n    def lengthOfLIS(self, nums: List[int]) -> int:\n        pass\n",
    javascript: "var lengthOfLIS = function(nums) {\n    \n};\n",
    java: "class Solution {\n    public int lengthOfLIS(int[] nums) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int lengthOfLIS(vector<int>& nums) {\n        \n    }\n};\n",
    go: "func lengthOfLIS(nums []int) int {\n    \n}\n",
  },
  "subsets": {
    python: "from typing import List\n\nclass Solution:\n    def subsets(self, nums: List[int]) -> List[List[int]]:\n        pass\n",
    javascript: "var subsets = function(nums) {\n    \n};\n",
    java: "import java.util.*;\n\nclass Solution {\n    public List<List<Integer>> subsets(int[] nums) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    vector<vector<int>> subsets(vector<int>& nums) {\n        \n    }\n};\n",
    go: "func subsets(nums []int) [][]int {\n    \n}\n",
  },
  "combination-sum": {
    python: "from typing import List\n\nclass Solution:\n    def combinationSum(self, candidates: List[int], target: int) -> List[List[int]]:\n        pass\n",
    javascript: "var combinationSum = function(candidates, target) {\n    \n};\n",
    java: "import java.util.*;\n\nclass Solution {\n    public List<List<Integer>> combinationSum(int[] candidates, int target) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    vector<vector<int>> combinationSum(vector<int>& candidates, int target) {\n        \n    }\n};\n",
    go: "func combinationSum(candidates []int, target int) [][]int {\n    \n}\n",
  },
  "permutations": {
    python: "from typing import List\n\nclass Solution:\n    def permute(self, nums: List[int]) -> List[List[int]]:\n        pass\n",
    javascript: "var permute = function(nums) {\n    \n};\n",
    java: "import java.util.*;\n\nclass Solution {\n    public List<List<Integer>> permute(int[] nums) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    vector<vector<int>> permute(vector<int>& nums) {\n        \n    }\n};\n",
    go: "func permute(nums []int) [][]int {\n    \n}\n",
  },
  "valid-anagram": {
    python: "class Solution:\n    def isAnagram(self, s: str, t: str) -> bool:\n        pass\n",
    javascript: "var isAnagram = function(s, t) {\n    \n};\n",
    java: "class Solution {\n    public boolean isAnagram(String s, String t) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    bool isAnagram(string s, string t) {\n        \n    }\n};\n",
    go: "func isAnagram(s string, t string) bool {\n    \n}\n",
  },
  "group-anagrams": {
    python: "from typing import List\n\nclass Solution:\n    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:\n        pass\n",
    javascript: "var groupAnagrams = function(strs) {\n    \n};\n",
    java: "import java.util.*;\n\nclass Solution {\n    public List<List<String>> groupAnagrams(String[] strs) {\n        \n    }\n}\n",
    cpp: "#include <vector>\n#include <string>\nusing namespace std;\n\nclass Solution {\npublic:\n    vector<vector<string>> groupAnagrams(vector<string>& strs) {\n        \n    }\n};\n",
    go: "func groupAnagrams(strs []string) [][]string {\n    \n}\n",
  },
  "longest-palindromic-substring": {
    python: "class Solution:\n    def longestPalindrome(self, s: str) -> str:\n        pass\n",
    javascript: "var longestPalindrome = function(s) {\n    \n};\n",
    java: "class Solution {\n    public String longestPalindrome(String s) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    string longestPalindrome(string s) {\n        \n    }\n};\n",
    go: "func longestPalindrome(s string) string {\n    \n}\n",
  },
  "reverse-bits": {
    python: "class Solution:\n    def reverseBits(self, n: int) -> int:\n        pass\n",
    javascript: "var reverseBits = function(n) {\n    \n};\n",
    java: "class Solution {\n    public int reverseBits(int n) {\n        \n    }\n}\n",
    cpp: "class Solution {\npublic:\n    uint32_t reverseBits(uint32_t n) {\n        \n    }\n};\n",
    go: "func reverseBits(num uint32) uint32 {\n    \n}\n",
  },
  "missing-number": {
    python: "from typing import List\n\nclass Solution:\n    def missingNumber(self, nums: List[int]) -> int:\n        pass\n",
    javascript: "var missingNumber = function(nums) {\n    \n};\n",
    java: "class Solution {\n    public int missingNumber(int[] nums) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int missingNumber(vector<int>& nums) {\n        \n    }\n};\n",
    go: "func missingNumber(nums []int) int {\n    \n}\n",
  },
  "jump-game": {
    python: "from typing import List\n\nclass Solution:\n    def canJump(self, nums: List[int]) -> bool:\n        pass\n",
    javascript: "var canJump = function(nums) {\n    \n};\n",
    java: "class Solution {\n    public boolean canJump(int[] nums) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    bool canJump(vector<int>& nums) {\n        \n    }\n};\n",
    go: "func canJump(nums []int) bool {\n    \n}\n",
  },
  "gas-station": {
    python: "from typing import List\n\nclass Solution:\n    def canCompleteCircuit(self, gas: List[int], cost: List[int]) -> int:\n        pass\n",
    javascript: "var canCompleteCircuit = function(gas, cost) {\n    \n};\n",
    java: "class Solution {\n    public int canCompleteCircuit(int[] gas, int[] cost) {\n        \n    }\n}\n",
    cpp: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int canCompleteCircuit(vector<int>& gas, vector<int>& cost) {\n        \n    }\n};\n",
    go: "func canCompleteCircuit(gas []int, cost []int) int {\n    \n}\n",
  },
};

export function getStarterCode(slug: string, language: Language): string {
  return STARTER_CODE[slug]?.[language] ?? DEFAULT[language];
}
